### ISSUE TITLE
Script is not able to pull elasticsearch init container

### ISSUE THREAD

**Issue by sanketnagdive** [project-sunbird/sunbird-ed-installer#9]
Elastic search init container was pulling image from a repo bitnami-shell which is moved to archival(name bitnami-shell-archived). Updated the scripts to use same image from repo bitnami-shell-archived.
cc @gandham-santhosh @mohitga @vinukumar-vs @santhosh-tg @keshavprasadms

**Comment by mohitga** [comment]
@keshavprasadms  do we need to use the archived image of elastic search?

**Comment by lazylua** [comment]
Hi @sanketnagdive Thank you for bringing this to notice. We're using standard bitnami charts for most dbs, and the es **version we're using is not the latest**. That's why we're using **the bitnami-shell, which come packaged with the version specific chart**. **It'll get updated, once we change the verison of elastic search**. For now, the image is only archived, and the usage is just to bootstrap the container, not to run any apps. So I don't think there are any issues. But if you want to use the latest image, you can override the global-values.yaml file to change the init container in `elasticsearch` block.

```
elastisearch:
  volumePermissions:
      image:
        registry: docker.io
        repository: bitnami/bitnami-shell
        tag: latest
  ```
